kumuluzee:
  name: users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BusersDS
      connection-url: jdbc:postgresql://postgres-users:5432/users
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
rest-properties:
  external-dependencies:
    accountoptions-service:
      enabled: false
kubernetes:
  accountoptions-service:
    address: http://169.51.26.156:30521
  users-service:
    address: http://169.51.26.156:30519