version: "3"
services:
  users-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    network_mode: "bridge"
    ports:
      - "5433:5432"
  users-service:
    image: users-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://docker.for.mac.localhost:5433/users
    ports:
      - "8082:8080"
    network_mode: "bridge"
    depends_on:
      - users-postgres